### ISSUE TITLE
Test cookies in Java to verify authentication scheme

### ISSUE THREAD

**Issue by cocolocomoco21** [cocolocomoco21/ULCRS#7]
For our UW NetID Service authentication, we want to have the FE handle authenticating users. As such, the FE will pass a cookie to the BE, and the BE will use this in its requests to the Drop-In server.

So, get a cookie from a request to https://tbrtest.engr.wisc.edu/ and use this in a request to get the same URL from within our Java server. This will verify that cookies can be used in Java, which verifies our authentication scheme, so that the FE can pass cookies to the BE in order for the BE to make requests.

Steps:
1) In a browser, go to https://tbrtest.engr.wisc.edu/ and log in with your UW NetID to get a fresh cookie
2) Copy the cookie(s) from the browser for this site
3) In the BE Java server, use some framework (Jetty?) to form an HTTP GET request to https://tbrtest.engr.wisc.edu/
4) Paste the cookie(s) into Java to use them in the GET request
5) Verify that the call is successful with the specific cookies. This shows that Java can use cookies from the FE to make authenticated requests

**Comment by Wrn2x** [comment]
Can successfully access SSO required url with cookies inserted.

**Comment by Wrn2x** [comment]
Test done. Connection test endpoint & implementation will not be included in next backend PR.
